backend:
  name: github
  repo: amfkut/kvenadm
  branch: main
  app_id: Ov23licY4ugAPP04CfbP

media_folder: "products/images"
public_folder: "/products/images"

collections:
  - name: "products"
    label: "Продукция"
    files:
      - name: "snow_crab"
        label: "Снежный краб"
        file: "data/products/snow_crab.json"
        fields:
          - label: "Заголовок"
            name: "title"
            widget: "string"
          - label: "Описание"
            name: "description"
            widget: "text"
          - label: "Изображение продукта"
            name: "image"
            widget: "image"
          - label: "Спецификации"
            name: "specs"
            widget: "object"
            fields:
              - label: "Состав"
                name: "Состав"
                widget: "text"
              - label: "Вес"
                name: "Вес"
                widget: "string"
              - label: "Упаковка"
                name: "Упаковка"
                widget: "string"
              - label: "Температура хранения"
                name: "Температура хранения"
                widget: "string"
              - label: "Срок годности"
                name: "Срок годности"
                widget: "string"
          - label: "Текст 'Где купить'"
            name: "buy_text"
            widget: "markdown"
          - label: "Ссылка покупки"
            name: "buy_link"
            widget: "string"
          - label: "Изображение 'Где купить'"
            name: "buy_img"
            widget: "image"
